name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  call-workflow:
    uses: stanlyonhack/headed/.github/workflows/workflow-1.yml@main

  call-workflow-passing-data:
    uses: stanlyonhack/headed/.github/workflows/workflow-1.yml@main
    with:
      username: stanlyonhack
    secrets:
      token: ${{ secrets.TOKEN }}
