name: CI

on:
  push:
    branches: [ main ]

jobs:
  call-workflow:
    uses: stanlyonhack/headed/.github/workflows/workflow-1.yml@﻿main #in main
    with:
      username: stanlyonhack
    secrets:
      token: ${{ secrets.TOKEN }}
