name: Reusable workflow example

on:
  workflow_call:
    inputs:
      username:
        required: true
        type: string
    secrets:
      token:
        required: true

jobs:
  example_job:
    name: Pass input and secrets to my-action
    runs-on: ubuntu-latest
    steps:
      - uses: ./.github/workflows/workflow-1.yml
        with:
          username: ${{ inputs.username }}
          token: ${{ secrets.TOKEN }}
          
      - uses: actions/checkout@v2
      - name: Run a one-line script
        run: echo Hello, world!
